### ISSUE TITLE
Add support for Mac

### ISSUE THREAD

**Issue by pgilmorepf** [PlayFab/MpsAgent#98] opened 2022-02-14 17:45 UTC
Customer PR:
https://github.com/PlayFab/MpsAgent/pull/30

This PR was old and was never integrated. It also contained changes that would negatively affect non-Mac platforms so it couldn't be merged. But it illustrates that it should not be a lot of work to add Mac support.

**Comment by dgkanatsios** [comment] 2022-02-14 18:18
duplicate of #81?

**Closed** 2022-02-14 18:59 UTC
